### PR TITLE
Additional configurations

### PR DESCRIPTION
**Pull request by KevinFCormier**
This PR adds parameterization for:
- hibernation and running schedules
- disabling either hibernation or resumption
- switching to an opt-in model
- using a custom image.
It also separates creation of the ClusterRole and ClusterRoleBinding into a separate step so the main deployment can be used on more tightly controlled environments.

The curator is modified to continue upon errors. This is so that it does not fail for ClusterDeployments it cannot modify (may be deliberately not allowed) or when it does not have permission to create Events. (A future enhancement would be to check if it has these permissions before attempting to patch ClusterDeployments or create Events.)

- [X] Remove Python version
- [X] Convert to using OCP Templates for easier parameterization
- [x] Fix `make` targets to actually create and delete resources
- [x] Fully implement the opt-in model

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@jnpacker Just wanted to create this PR to give you a heads up what I'm working on. I still need to test all of this and I will finish setting up the OPT-IN model as well before I request full review and merge.

**Comment by KevinFCormier** [comment]
@jnpacker Everything seems to be working locally, but I'm getting this error from the pod. Have you seen this before?
image

**Comment by KevinFCormier** [comment]
@jnpacker I had to set `GOOS=linux GOARCH=amd64` for the go build.

**Review by jnpacker — APPROVED** [review]
Looks good. 
Thank you for implement all these new capabilities!

**Comment by jnpacker** [comment]
https://github.com/open-cluster-management/hibernate-cronjob/issues/6

**Pull request merged**
